container:
  image: python:latest

test_task:

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  test_script: |
    set -x
    ls -l
    python3 -c 'import platform; print(platform.machine(), platform.uname())'  # , platform.dist())'
    brew install csound

    python3 -m venv .venv
    source .venv/bin/activate
    
    python3 -m pip install .
    cd test
    python3 test1.py -o test1-mac-arm64.wav
    python3 test2.py
    
    ls -l
    cd ..
        
  binaries_artifacts:
    path: test/*.wav



#
# OSX
#
#osx_task:
#  auto_cancellation: true

#
#  check_script:
#    - python3 -c "import platform; print(platform.machine(), platform.architecture())"

